"""
Phase 1 — execute every query in sql/queries.sql and render the results
as a Markdown findings report.

Run:  python src/run_sql_report.py
Out:  reports/sql_results.md
"""
from __future__ import annotations

import re
import sqlite3
import sys
from pathlib import Path

import pandas as pd

sys.path.append(str(Path(__file__).resolve().parent))
from config import DB_PATH, REPORTS_DIR, SQL_DIR  # noqa: E402


def parse_queries(path: Path) -> list[dict]:
    """Walk queries.sql line by line, collecting (id, owner, question, sql).

    A block opens at a `-- Qnn | owner` header, its question is the first
    quoted comment line after it, and its SQL is every non-comment line
    until the next header.
    """
    blocks: list[dict] = []
    current: dict | None = None
    sql_lines: list[str] = []

    def flush() -> None:
        if current is not None:
            sql = "\n".join(sql_lines).strip()
            if sql:
                current["sql"] = sql
                blocks.append(current)

    for raw in path.read_text().splitlines():
        header = re.match(r"--\s*(Q\d{2})\s*\|\s*(.+)", raw.strip())
        if header:
            flush()
            current = {
                "id": header.group(1),
                "owner": header.group(2).strip(),
                "question": "",
            }
            sql_lines = []
            continue
        if current is None:
            continue
        stripped = raw.strip()
        if stripped.startswith("--"):
            quoted = re.search(r'"(.+?)"', stripped)
            if quoted and not current["question"]:
                current["question"] = quoted.group(1)
            continue
        sql_lines.append(raw)

    flush()
    return blocks


def main() -> None:
    queries = parse_queries(SQL_DIR / "queries.sql")
    print(f"parsed {len(queries)} queries from queries.sql")

    lines = [
        "# Phase 1 — SQL Findings",
        "",
        "Auto-generated by `src/run_sql_report.py`. Every table below is the live",
        "output of the correspondingly numbered query in `sql/queries.sql`,",
        "run against `db/nexatel.db` (7,043 subscribers, 4 normalised tables).",
        "",
    ]

    with sqlite3.connect(DB_PATH) as conn:
        for q in queries:
            df = pd.read_sql_query(q["sql"], conn)
            print(f"  {q['id']}  {len(df)} row(s)")
            lines += [
                f"## {q['id']} — {q['question']}",
                f"*Asked by: {q['owner']}*",
                "",
                df.to_markdown(index=False),
                "",
            ]

    out = REPORTS_DIR / "sql_results.md"
    out.write_text("\n".join(lines))
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
